=== JaeHan-Kim/java76s/xml01/step03/Test07.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!-- 속성의 타입(식별자참조)
	IDREF		ID 값을 저장해야 한다.
 -->
<!ELEMENT projects (student*,project*)>
<!ELEMENT student EMPTY>
<!ATTLIST	student
	name 		NMTOKEN #REQUIRED
	gender 	(man|woman|trans) "man"
	email		ID #REQUIRED
	tel			NMTOKENS #IMPLIED
>

<!ELEMENT project EMPTY>
<!ATTLIST project
	title		CDATA #REQUIRED
	owner		IDREF #REQUIRED
	members	IDREFS	#IMPLIED
>

=== JaeHan-Kim/java76s/xml01/step03/Test07.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projects SYSTEM "Test07.dtd">

<projects>
<student name="홍길동" gender="man" email="hong" />
<student name="임꺽정" gender="man" email="leem" />
<student name="유관순" gender="man" email="yoo" />
<student name="김원봉" gender="man" email="kim" />
<student name="김구" gender="man" email="kimgu" />
<student name="안중근" gender="man" email="ahn" />
<student name="윤봉길" gender="man" email="yoon" 
		 tel="111-1111 222-2222 333-3333" />
		
<!-- <project title="프로젝트1" owner="hon" /> 
	오류! hon 이라는 ID가 존재하지 않는다 -->
<project title="프로젝트2" owner="hong" members="hong kim"/>
<project title="프로젝트3" owner="hong" members="hong kim"/>
<project title="프로젝트3" owner="hong" members="hong kim leem"/>
</projects>
